In [1]:
import pandas as pd

In [2]:
crime = pd.read_table('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv', sep=',')

In [3]:
crime.head()

   Year  Population    Total  ...  Burglary  Larceny_Theft  Vehicle_Theft
0  1960   179323175  3384200  ...    912100        1855400         328200
1  1961   182992000  3488000  ...    949600        1913000         336000
2  1962   185771000  3752200  ...    994300        2089600         366800
3  1963   188483000  4109500  ...   1086400        2297800         408300
4  1964   191141000  4564600  ...   1213200        2514400         472800

[5 rows x 12 columns]

In [4]:
#What is the type of the columns?

crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

In [5]:
#Convert the type of the column Year to datetime64

crime['Year'] = pd.to_datetime(crime['Year'], format='%Y')
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     datetime64[ns]
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: datetime64[ns](1), int64(11)
memory usage: 5.3 KB

In [6]:
#Set the Year column as the index of the dataframe

crime.set_index('Year', drop=True)
crime.head()

        Year  Population    Total  ...  Burglary  Larceny_Theft  Vehicle_Theft
0 1960-01-01   179323175  3384200  ...    912100        1855400         328200
1 1961-01-01   182992000  3488000  ...    949600        1913000         336000
2 1962-01-01   185771000  3752200  ...    994300        2089600         366800
3 1963-01-01   188483000  4109500  ...   1086400        2297800         408300
4 1964-01-01   191141000  4564600  ...   1213200        2514400         472800

[5 rows x 12 columns]

In [7]:
#Delete the Total column
crime.drop('Total', axis = 1).head()

        Year  Population  Violent  ...  Burglary  Larceny_Theft  Vehicle_Theft
0 1960-01-01   179323175   288460  ...    912100        1855400         328200
1 1961-01-01   182992000   289390  ...    949600        1913000         336000
2 1962-01-01   185771000   301510  ...    994300        2089600         366800
3 1963-01-01   188483000   316970  ...   1086400        2297800         408300
4 1964-01-01   191141000   364220  ...   1213200        2514400         472800

[5 rows x 11 columns]

In [8]:
#Group the year by decades and sum the values

crimes = crime.resample('10AS').sum()

population = crime['Population'].resample('10AS').max()

crimes['Population'] = population

crimes

TypeError: ignored

In [9]:
#What is the mos dangerous decade to live in the US

crime.idxmax(0)

TypeError: ignored