In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
wine = pd.read_csv(url)

In [3]:
wine.head()

   1  14.23  1.71  2.43  15.6  127  ...   .28  2.29  5.64  1.04  3.92  1065
0  1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
1  1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
2  1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
3  1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735
4  1  14.20  1.76  2.45  15.2  112  ...  0.34  1.97  6.75  1.05  2.85  1450

[5 rows x 14 columns]

Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [4]:
wine = wine.drop(wine.columns[[0,3,6,8,10,12,13]], axis = 1)

In [5]:
wine.head()

   14.23  1.71  15.6  127  3.06  2.29  1.04
0  13.20  1.78  11.2  100  2.76  1.28  1.05
1  13.16  2.36  18.6  101  3.24  2.81  1.03
2  14.37  1.95  16.8  113  3.49  2.18  0.86
3  13.24  2.59  21.0  118  2.69  1.82  1.04
4  14.20  1.76  15.2  112  3.39  1.97  1.05

Step 5. Assign the columns as below:
The attributes are (dontated by Riccardo Leardi, riclea '@' anchem.unige.it):

1) alcohol  

2) malic_acid

3) alcalinity_of_ash

4) magnesium

5) flavanoids

6) proanthocyanins

7) hue

In [6]:
wine.columns = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids', 'proanthocyanins', 'hue']
wine.head()

   alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0    13.20        1.78               11.2  ...        2.76             1.28  1.05
1    13.16        2.36               18.6  ...        3.24             2.81  1.03
2    14.37        1.95               16.8  ...        3.49             2.18  0.86
3    13.24        2.59               21.0  ...        2.69             1.82  1.04
4    14.20        1.76               15.2  ...        3.39             1.97  1.05

[5 rows x 7 columns]

Step 6. Set the values of the first 3 rows from alcohol as NaN

In [7]:
wine.iloc[0:3, 0] = np.nan
wine.head()

   alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0      NaN        1.78               11.2  ...        2.76             1.28  1.05
1      NaN        2.36               18.6  ...        3.24             2.81  1.03
2      NaN        1.95               16.8  ...        3.49             2.18  0.86
3    13.24        2.59               21.0  ...        2.69             1.82  1.04
4    14.20        1.76               15.2  ...        3.39             1.97  1.05

[5 rows x 7 columns]

Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [8]:
wine.iloc[2:4, 3] = np.nan
wine.head()

   alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0      NaN        1.78               11.2  ...        2.76             1.28  1.05
1      NaN        2.36               18.6  ...        3.24             2.81  1.03
2      NaN        1.95               16.8  ...        3.49             2.18  0.86
3    13.24        2.59               21.0  ...        2.69             1.82  1.04
4    14.20        1.76               15.2  ...        3.39             1.97  1.05

[5 rows x 7 columns]

Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [9]:
wine.alcohol.fillna(10, inplace= True)
wine.magnesium.fillna(100, inplace = True)

In [10]:
wine.head()

   alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0    10.00        1.78               11.2  ...        2.76             1.28  1.05
1    10.00        2.36               18.6  ...        3.24             2.81  1.03
2    10.00        1.95               16.8  ...        3.49             2.18  0.86
3    13.24        2.59               21.0  ...        2.69             1.82  1.04
4    14.20        1.76               15.2  ...        3.39             1.97  1.05

[5 rows x 7 columns]

Step 9. Count the number of missing values

In [11]:
wine.isna().sum()

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

Step 10. Create an array of 10 random numbers up until 10

In [13]:
random = np.random.randint(10, size=10)
random

array([1, 5, 3, 2, 1, 6, 5, 5, 0, 4])

Step 11. Use random numbers you generated as an index and assign NaN value to each of cell.

In [14]:
wine.alcohol[random] = np.nan
wine.head(10)

   alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0      NaN        1.78               11.2  ...        2.76             1.28  1.05
1      NaN        2.36               18.6  ...        3.24             2.81  1.03
2      NaN        1.95               16.8  ...        3.49             2.18  0.86
3      NaN        2.59               21.0  ...        2.69             1.82  1.04
4      NaN        1.76               15.2  ...        3.39             1.97  1.05
5      NaN        1.87               14.6  ...        2.52             1.98  1.02
6      NaN        2.15               17.6  ...        2.51             1.25  1.06
7    14.83        1.64               14.0  ...        2.98             1.98  1.08
8    13.86        1.35               16.0  ...        3.15             1.85  1.01
9    14.10        2.16               18.0  ...        3.32             2.38  1.25

[10 rows x 7 columns]

Step 12. How many missing values do we have?

In [15]:
wine.isna().sum()

alcohol              7
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

step 13. Delete the rows that contain missing values

In [16]:
wine = wine.dropna(axis=0, how='any')
wine.head()

    alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
7     14.83        1.64               14.0  ...        2.98             1.98  1.08
8     13.86        1.35               16.0  ...        3.15             1.85  1.01
9     14.10        2.16               18.0  ...        3.32             2.38  1.25
10    14.12        1.48               16.8  ...        2.43             1.57  1.17
11    13.75        1.73               16.0  ...        2.76             1.81  1.15

[5 rows x 7 columns]

Step 14. Print only the non-null values in alcohol

In [17]:
mask = wine.alcohol.notna()
mask

7      True
8      True
9      True
10     True
11     True
       ...
172    True
173    True
174    True
175    True
176    True
Name: alcohol, Length: 170, dtype: bool

In [18]:
wine.alcohol[mask]

7      14.83
8      13.86
9      14.10
10     14.12
11     13.75
       ...
172    13.71
173    13.40
174    13.27
175    13.17
176    14.13
Name: alcohol, Length: 170, dtype: float64

Step 15. Reset the index, so it starts with 0 again

In [20]:
wine.reset_index(drop=True)

     alcohol  malic_acid  alcalinity_of_ash  ...  flavanoids  proanthocyanins   hue
0      14.83        1.64               14.0  ...        2.98             1.98  1.08
1      13.86        1.35               16.0  ...        3.15             1.85  1.01
2      14.10        2.16               18.0  ...        3.32             2.38  1.25
3      14.12        1.48               16.8  ...        2.43             1.57  1.17
4      13.75        1.73               16.0  ...        2.76             1.81  1.15
..       ...         ...                ...  ...         ...              ...   ...
165    13.71        5.65               20.5  ...        0.61             1.06  0.64
166    13.40        3.91               23.0  ...        0.75             1.41  0.70
167    13.27        4.28               20.0  ...        0.69             1.35  0.59
168    13.17        2.59               20.0  ...        0.68             1.46  0.60
169    14.13        4.10               24.5  ...        0.76             1.35  0.61

[170 rows x 7 columns]

BONUS: Create your own question and answer it.

Describe the data

In [21]:
wine.describe()

          alcohol  malic_acid  ...  proanthocyanins         hue
count  170.000000  170.000000  ...       170.000000  170.000000
mean    12.960353    2.351176  ...         1.574118    0.954565
std      0.800806    1.139295  ...         0.570756    0.233142
min     11.030000    0.740000  ...         0.410000    0.480000
25%     12.332500    1.575000  ...         1.225000    0.772500
50%     12.975000    1.845000  ...         1.540000    0.960000
75%     13.627500    3.157500  ...         1.915000    1.120000
max     14.830000    5.800000  ...         3.580000    1.710000

[8 rows x 7 columns]